### ISSUE TITLE
Install of oh-my-zsh needs modification to avoid skipping rest of setup/zsh

### ISSUE THREAD

**Issue by kyleniemeyer** [benbalter/dotfiles#25]
Hi there! I've found this setup extremely useful, so thanks for making it available.

As I've been customizing it for myself, I realized that `script/zsh` doesn't currently work as designed, because the oh-my-zsh install script causes the setup script to exit prematurely, due to the `env zsh -l` at the end. 

(It seems this is a known issue for a number of oh-my-zsh users, as there are more than a couple of issues and PRs over there to add, e.g., a `--silent` flag.)

In the meantime, one suggested fix is to use sed to remove that line (https://github.com/robbyrussell/oh-my-zsh/issues/5873#issuecomment-395952239), and I've modified it to use wget instead:
```
sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sed 's:env zsh -l::g' | sed 's:chsh -s .*$::g')"
```
If you replace the current line 12 in `setup/zsh` with this, then the script can move past this point.

**Comment by benbalter** [comment]
@kyleniemeyer this is great. Thank you! Would you be willing to submit a pull request with this change?

**Comment by kyleniemeyer** [comment]
Sure thing, see #26
